module.exports = {
  body_material: 'body_material',
  brand_name: 'brand_name',
  camera: 'camera_id',
  cashiers_check: 'check_id',
  check_body: 'check_body',
  color: 'color',
  customer: 'customer_id',
  device: 'device_id',
  lens_material: 'lens_material',
  memory: 'memory',
  os: 'os',
  payment_type: 'payment_type',
  screen: 'screen_id',
  screen_size: 'screen_size',
  screen_type: 'screen_type',
  stabilazer: 'stabilazer',
  type: 'type',
  type_charge: 'type_charge',
  warehouse: 'warehouse_id',
  wholesale_supplier: 'personal_account',
};
